@echo off
inc2l aclui.inc
inc2l activeds.inc
inc2l adme.inc
inc2l adptif.inc
inc2l adsiid.inc
inc2l advapi32.inc
inc2l aftpapi.inc
inc2l authz.inc
inc2l bdnapi.inc
inc2l bhmon.inc
inc2l bignumsdk.inc
inc2l cap.inc
inc2l certadm.inc
inc2l certidl.inc
inc2l ciuuid.inc
inc2l cluadmex.inc
inc2l clusapi.inc
inc2l comctl32.inc
inc2l comdlg32.inc
inc2l comsvcs.inc
inc2l confid.inc
inc2l crypt32.inc
inc2l cryptnet.inc
inc2l d3dim.inc
inc2l d3drm.inc
inc2l d3dx.inc
inc2l d3dxd.inc
inc2l d3dxof.inc
inc2l dapi.inc
inc2l dbghelp.inc
inc2l dbsetsst.inc
inc2l ddraw.inc
inc2l dflayout.inc
inc2l dhcpcsvc.inc
inc2l dinput.inc
inc2l RESOURCE.H
inc2l dlcapi.inc
inc2l dmapiw32.inc
inc2l dnsapi.inc
inc2l dplay.inc
inc2l dplayx.inc
inc2l dsetup.inc
inc2l dsound.inc
inc2l dsprop.inc
inc2l dsuiext.inc
inc2l dtccfg.inc
inc2l dtccm.inc
inc2l dtcuic.inc
inc2l dtcuis.inc
inc2l dtcutil.inc
inc2l edbbcli.inc
inc2l fcachdll.inc
inc2l fci.inc
inc2l fdi.inc
inc2l filter.inc
inc2l fmistr32.inc
inc2l framedyd.inc
inc2l INC2L.EXE
inc2l bldlibs.bat
inc2l framedyn.inc
inc2l friendly.inc
inc2l gdi32.inc
inc2l glaux.inc
inc2l glu32.inc
inc2l gpedit.inc
inc2l gtrtst32.inc
inc2l hexedit.inc
inc2l hlink.inc
inc2l htmlhelp.inc
inc2l icm32.inc
inc2l icmui.inc
inc2l ihvlink.inc
inc2l imagehlp.inc
inc2l imm32.inc
inc2l interfac.inc
inc2l iphlpapi.inc
inc2l iprop.inc
inc2l kernel32.inc
inc2l ksproxy.inc
inc2l loadperf.inc
inc2l logmgr.inc
inc2l lz32.inc
inc2l mapi32.inc
inc2l mapiw32.inc
inc2l mdhcpid.inc
inc2l measure.inc
inc2l mgmtapi.inc
inc2l minidump.inc
inc2l mmc.inc
inc2l mobsync.inc
inc2l mpr.inc
inc2l mprapi.inc
inc2l mqmail.inc
inc2l mqrt.inc
inc2l msacm32.inc
inc2l mscms.inc
inc2l msdasc.inc
inc2l msdtcprx.inc
inc2l msdtctm.inc
inc2l msi.inc
inc2l msimg32.inc
inc2l msmqep.inc
inc2l mspatchc.inc
inc2l mspbase.inc
inc2l mspid.inc
inc2l msrating.inc
inc2l mssachlp.inc
inc2l mswsock.inc
inc2l mswtecom.inc
inc2l mtx.inc
inc2l nal.inc
inc2l nddeapi.inc
inc2l netapi32.inc
inc2l nmapi.inc
inc2l npptools.inc
inc2l ntdsapi.inc
inc2l ntdsbcli.inc
inc2l ntmsapi.inc
inc2l ntquery.inc
inc2l odbc32.inc
inc2l odbcbcp.inc
inc2l odbccp32.inc
inc2l ole32.inc
inc2l oleacc.inc
inc2l oleaut32.inc
inc2l oledb.inc
inc2l oledbd.inc
inc2l oledlg.inc
inc2l olepro32.inc
inc2l opengl32.inc
inc2l osptk.inc
inc2l parser.inc
inc2l patchwiz.inc
inc2l pdh.inc
inc2l penter.inc
inc2l proptag.inc
inc2l psapi.inc
inc2l qosname.inc
inc2l quartz.inc
inc2l randlib.inc
inc2l rasapi32.inc
inc2l rasdlg.inc
inc2l rassapi.inc
inc2l rendid.inc
inc2l resutils.inc
inc2l riched20.inc
inc2l rpcndr.inc
inc2l rpcns4.inc
inc2l rpcrt4.inc
inc2l rsa32sdk2.inc
inc2l rtflib32.inc
inc2l rtm.inc
inc2l rtutils.inc
inc2l sadapi.inc
inc2l scarddlg.inc
inc2l scrnsave.inc
inc2l scrnsavw.inc
inc2l sdpblbid.inc
inc2l secur32.inc
inc2l sens.inc
inc2l sensapi.inc
inc2l setupapi.inc
inc2l sfc.inc
inc2l shell32.inc
inc2l shfolder.inc
inc2l shlwapi.inc
inc2l slbs.inc
inc2l snacli.inc
inc2l snanls.inc
inc2l snmpapi.inc
inc2l sporder.inc
inc2l sqlakw32.inc
inc2l sti.inc
inc2l strmbasd.inc
inc2l strmbase.inc
inc2l svcguid.inc
inc2l t3iid.inc
inc2l tapi32.inc
inc2l thunk32.inc
inc2l tmuid.inc
inc2l toolbar.inc
inc2l traffic.inc
inc2l trnsdt.inc
inc2l tssutil.inc
inc2l url.inc
inc2l urlmon.inc
inc2l user32.inc
inc2l userenv.inc
inc2l usp10.inc
inc2l uuid.inc
inc2l vdmdbg.inc
inc2l version.inc
inc2l vfw32.inc
inc2l wappc32.inc
inc2l wbemuuid.inc
inc2l wcpic32.inc
inc2l webpost.inc
inc2l wiaguid.inc
inc2l wincsv32.inc
inc2l winfax.inc
inc2l wininet.inc
inc2l winmm.inc
inc2l winrui32.inc
inc2l winscard.inc
inc2l winsli32.inc
inc2l winspool.inc drv
inc2l winstrm.inc
inc2l wintrust.inc
inc2l wow32.inc
inc2l ws2_32.inc
inc2l wsnmp32.inc
inc2l wsock32.inc
inc2l wtsapi32.inc

move *.lib \masm32\lib
