  ; ===========================================
  ; tssutil.inc copyright MASM32 1998 - 2005
  ; ===========================================

IFNDEF TSSUTIL_INC
TSSUTIL_INC equ <1>

R0PAX PROTO :DWORD,:DWORD
_CxxThrowException PROTO :DWORD,:DWORD

ELSE
echo -----------------------------------------
echo WARNING Duplicate include file tssutil.inc
echo -----------------------------------------
ENDIF
